import { Geist, Geist_Mono, Rammetto_One } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const ramettoOne = Rammetto_One({
  weight: "400",
  variable: "--font-ramettoOne",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <h1 className="text-center">Snapshot</h1>
        <nav className="text-center flex justify-around">
          <Link href={"/"}>Home</Link>

          <Link href="/posts">Your posts</Link>
          <Link href="/newPost">Add post</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
